name = "img"
main = "./src/index.js"
compatibility_date = "2022-11-08"

kv_namespaces = [
  { binding = "note", id = "1c4dc889c6c640288a1d2098609ab67e",preview_id='1c4dc889c6c640288a1d2098609ab67e'}
]
[site]
bucket = "./static/dist"
